apiVersion: v1
kind: Pod
metadata:
  name: pod3
spec:
  initContainers:
  - name: install
    image: ubuntu
    volumeMounts:
      - name: workdir
        mountPath: /code
    command: ['bin/sh','-c','apt-get update; apt-get install git -y; git clone https://github.com/damiangralek/poznajkubernetes /code; sleep 30']
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: workdir
        mountPath: /usr/share/nginx/html
  volumes:
    - name: workdir
      emptyDir: {}
